### ISSUE TITLE
Mouse unusable in a match

### ISSUE THREAD

**Issue by SirSharpest** [gamax92/wine-overwatch#1]
Everything works with this perfectly, EXCEPT for the mouse when I'm in game, it just spins continuously. 

Have spoken to a few people on the Lutris discord and they've said the issue has been reported. 

What details can I provide to help? 

I'm on Arch with latest drivers and issues of Wine-overwatch patch and wine 2.3 staging. Running nVidia drivers through bumblebee.

**Comment by gamax92** [comment]
This is not an appropriate place to report this bug, I'm not a wine developer and have barely looked into wine's codebase, please file a bug on wine's bug tracker.
