### ISSUE TITLE
Control problem

### ISSUE THREAD

**Issue by zaazz55** [gamax92/wine-overwatch#2]
I'm using Lutris to launch this and everything seems to load fine until I get into a game. Once in the game I lose control of my mouse and keyboard until I ALT+TAB out and back in. After I'm re-attached to the window it's as if I am holding down the "turn left" keyboard button. The 1st person view is always spinning left. I am wondering if there's anything in the wine config that would help me resolve this. Otherwise it does seem to launch ok.

**Comment by Paktosan** [comment]
I have that problem too that I am constantly viewing upward.

**Comment by Minkiu** [comment]
I don't know if this should be reported here, but I am in the same boat:

Game starts, select hero, and I cant do anything, just move the moise cursor around.

Alt+tab, games seems to work, but i have either vertical or horizontal constant movement (as you described).

After dying and seeing the kill cam, I get a black screen except for the HUD, and I can actually control the pj, do skills, open menu, etc... Sometimes it just frozes. So i need to quit the game.

Got me into a -75% exp penalty for 15 matches, of all the times I tried to play it 🙃
