### ISSUE TITLE
Mouse drag issue

### ISSUE THREAD

**Issue by sambow23** [gamax92/wine-overwatch#26]

**Comment by sambow23** [comment]
Whenever I switch to XP mode in wine, it causes the mouse to drag whenever I look around. It's been happening to me on multiple linux distros and I have no idea what's causing it.

**Comment by sambow23** [comment]
Oddly it works just fine whenever I set the windows version to 7, but the game halts randomly.

**Comment by sambow23** [comment]
[Here's a video of what I mean](https://www.youtube.com/watch?v=jnxO2_R5bYs&feature=youtu.be)

**Comment by sambow23** [comment]
Well I found a workaround, opening Overwatch from the terminal without the Blizzard App seems work just fine

**Comment by Paktosan** [comment]
Can you PLEASE just write one comment or edit the first, when commenting in short bursts. Some people, who subscribed to every issue automatically, will get an email for every single comment you write...

**Comment by sambow23** [comment]
Yeah sorry, I had some issues on my end and it seemed like I couldn't post anything.
