### ISSUE TITLE
NTDLL anticheat patches

### ISSUE THREAD

**Issue by Thaodan** [gamax92/wine-overwatch#29]
Can you point out which patches do this stuff so they can be applied to plain wine or staging?

**Comment by zekesonxx** [comment]
The latest version of the wine-overwatch patches, relative to 2.15-staging, is 692ac4997323a2e2551a0728e90cbd855becb38d.

The patches to `dlls/ntdll` and `tools` should be all the ntdll patches that make up. You'll probably also need the kernel32 patch to get Overwatch to run at all. As far as I know/can tell, the rest of the patches aren't needed to get the game to *run*, but they are needed to get the game to the playable state it's in.

If you look through [Andrew Wesie's original patches](https://bitbucket.org/awesie/wine-overwatch/commits/all) you can find the original version of these patches, relative to 2.0 mainline.

**Comment by awesie** [comment]
The relevant files in that commit are dlls/ntdll/* and tools/*. The biggest change is the way the fake NTDLL is constructed. I think there has been some movement in wine-staging to improve the fake DLLs, but I am not sure if it is sufficient.

**Comment by gamax92** [comment]
If I remember correctly, the changes wine-staging did for the fake DLLs only applied to the 32bit variants

**Comment by Thaodan** [comment]
Ok, I thought these changes make wow running.
I thought I can only apply these changes to staging to fix wow as the overwatch branch has other issues like this:
https://bugs.winehq.org/show_bug.cgi?id=43641

**Comment by zekesonxx** [comment]
Yeah I was guessing that.

You certainly could manually apply just the ntdll patches to Wine-Staging and try WoW that way.

**Comment by gamax92** [comment]
There's also the overwatch-2.0 branch you can use for WoW, DX9 only though. Reason being the old CSMT patchset that used to only work for DX9 was faster than the current version that works for both DX9 and DX10/11

**Comment by Thaodan** [comment]
does it have the same issue with the subsurface, ressource thing?

**Comment by gamax92** [comment]
That commit is in that branch as well, so yes.

@awesie Thinking this commit is causing issues with WoW: https://bitbucket.org/awesie/wine-overwatch/commits/c218450374b8fd4926ae0403d7fa56ef79b7ddac  
And the relevant bug report: https://bugs.winehq.org/show_bug.cgi?id=43641

**Comment by gamax92** [comment]
@Thaodan Staging 2.16 now has patches that generates better fake DLLs for 64bit, so I'm assuming that WoW will work normally again without any of the Overwatch patches.

For that matter, Overwatch now boots up on Staging 2.16, albeit with graphics glitches due to no flat interpolation support yet.
