### ISSUE TITLE
Can you make a mac os version?

### ISSUE THREAD

**Issue by Scurax** [gamax92/wine-overwatch#30]

**Comment by Paktosan** [comment]
No, this is currently not possible mainly because the OpenGL version used in macOS is too old. It is not likely that this will change in the near future. Also please read the FAQ first before posting an issue since this was already answered there.

**Comment by zekesonxx** [comment]
[Q. Will this work on macOS?](https://github.com/gamax92/wine-overwatch/wiki/FAQ#q-will-this-work-on-macos)

TL;DR: unless you want to fund a couple Wine devs for a few months, not anytime soon.
