### ISSUE TITLE
wine-overwatch-2.16 CSMT causes crash soon after getting to menu

### ISSUE THREAD

**Issue by sirus20x6** [gamax92/wine-overwatch#31]
in wine-overwatch-2.16 enabling csmt causes the game to hang soon after logging in. within a second or two.

**Comment by sigzegv** [comment]
I think I have the same issue, with this error `../../../wine-overwatch/dlls/wined3d-csmt/../wined3d/wined3d_private.h :4417 : wined3d_from_cs:  assertion « cs->thread_id == GetCurrentThreadId() » failed.`

**Comment by IngeniousDox** [comment]
I confirm the crash with 2 different builds of 2.16.

Though, I don't think CSMT is needed atm, at least not for NVidia users that use __GL_THREADED_OPTIMIZATIONS. I got 60 fps on low without issues in 2.16.

**Comment by sirus20x6** [comment]
I'm on opensource AMD. Performance isn't terrible, but it also isn't fantastic. although CSMT also increased the number of freezes in previous builds, but i could normally play for about an hour or so without a crash.

**Comment by IngeniousDox** [comment]
Have you tried: mesa_glthread: 'true'? I hear good things about it.

**Comment by sirus20x6** [comment]
mesa_glthread: 'true' is actually the default now. I have an AMD 290 that's solder unlocked to a 290x and i play at 1600x900. performance is mostly ok but I still get hitching often and sometimes performance seems to be bad without reason and then get better also without reason.

**Comment by IngeniousDox** [comment]
Most likely culprit is the shader cache, it is empty and it calculates the shaders (which lags you). Then when it is has most shaders for that map / players, your game will run better.

For me with NVidia, the cache can become up to 130mb, so much that I actually had to start setting a shader path to a seperate dir, otherwise there was a chance it got pruned when the total cache reached 256mb. I started setting the cache patch on all my games now so that doesn't happen anymore.

**Comment by gamax92** [comment]
I ... I swear this was no longer happening, hence why I removed the commit that comments out this assert.

oops?

**Comment by gamax92** [comment]
Oh well, after getting many reports this is still an issue I've added it back into the repository, rebuild wine.

**Comment by sirus20x6** [comment]
there are ways that it seems like it may be the shader cache causing my performance issues like it being worst when there are characters in view. there are also ways in which it does not seem like shader cache such as it not necessarily getting better or worse with time and sometimes I launch the game and it runs perfectly without any lag hitches. either way mesa_glthread: 'true' is not enough to give me stable fps all the time and for me CSMT worked on 2.13, 2.14, 2.15 and does not in 2.16
