### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by roboso** [gamax92/wine-overwatch#36]
[ow-1506096360.log.tar.gz](https://github.com/gamax92/wine-overwatch/files/1325481/ow-1506096360.log.tar.gz)

**Comment by zekesonxx** [comment]
You're right, that is a game crash.

What wine-ow version were you using? Were you doing anything in particular when it occurred? Can you reproduce the circumstances of the crash?

**Comment by roboso** [comment]
wine staging 2.17 wine-ow branc master

**Comment by zekesonxx** [comment]
> Were you doing anything in particular when it occurred? Can you reproduce the circumstances of the crash?

**Comment by roboso** [comment]
with the new ow no more crash update yet, but I do not see the list of my friends.
