### ISSUE TITLE
Not able to sign into Blizzard App

### ISSUE THREAD

**Issue by sambow23** [gamax92/wine-overwatch#37]
I just reinstalled Arch Linux two times for good measures, but whenever you install and then launch the Blizzard App, it shows the normal login screen, but there is no way to actually log in...
[Image](https://i.imgur.com/qtSxoTR.png)

**Comment by gamax92** [comment]
What Windows version do you have wine set to in winecfg?

**Comment by sambow23** [comment]
Windows 10, I also tried XP, does the same thing.

**Comment by gamax92** [comment]
Not sure, I can get the glitched version where the top don't work but the bottom prompts do.
![glitch](https://user-images.githubusercontent.com/815145/30839561-f1f5ccfe-a22f-11e7-8bbb-f5a356389316.png)

**Comment by sambow23** [comment]
Yeah I see what you're talking about, I was trying to get that one to pop up, but it seems luck has failed on me. I'll see if I can get into it

**Comment by gamax92** [comment]
You can try purging the wine ie cache at `~/.wine/drive_c/users/$USER/Local\ Settings/Temporary\ Internet\ Files/`

**Comment by sambow23** [comment]
I don't have a local in that directory. But apparently I can actually get in without logging in, and I can install Overwatch. But wouldn't I need to be logged into the Blizzard App for me to launch it?

**Comment by gamax92** [comment]
If you launch Overwatch directly, it will just ask you to login in game.

**Comment by sambow23** [comment]
Ah I see, sorry for the dumb question. :)
