### ISSUE TITLE
LoD black ground textures (World of Warcraft x64)

### ISSUE THREAD

**Issue by d3rrial** [gamax92/wine-overwatch#39]
With the newest build on x64 with the freetype patch applied https://source.winehq.org/git/wine.git/?a=commit;h=d82321006de92dcd74465c905121618a76eae76a the ground seems to be uniformely #000000 in color, except when its outside of the high detail drawing range, as soon as lower resolution textures are loaded, the ground is normally textured.

Works flawlessly with your 2.16 build, just doesn't work with the 2.17 build. This issue only seems to affect ground textures as far as I can tell and is permanent, or rather consistently reproducible.

**Comment by zekesonxx** [comment]
The only patch wine-ow has now is a fixed FlashWindowEx, which wouldn't affect this at all. Since this isn't about our patch or Overwatch, I'm closing this.

You should open a Wine issue about this, they're the correct people to talk to: https://bugs.winehq.org/
