### ISSUE TITLE
Wine version mismatch

### ISSUE THREAD

**Issue by wascardev** [gamax92/wine-overwatch#4]
I can't launch Battle.net Launcher. Tested with 2.7 and 2.6.

OS : Linux Mint 18.1

Logs :
```
wine client error:0: version mismatch 447/528.
Your wineserver binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
err:process:start_wineboot failed to start wineboot, err 1359
```

**Comment by gamax92** [comment]
Make sure you've uninstalled any copy of wine from Linux Mint's package manager and killed any copy of wineserver that was still running.

Also ... 447 corresponds to a really old version of Wine 1.7.1 released 4 years ago.

**Comment by wascardev** [comment]
I uninstalled wine package, i'ts works, thanks.
