### ISSUE TITLE
Game Initialization Failed

### ISSUE THREAD

**Issue by Amblypygid** [gamax92/wine-overwatch#9]
I have had a lot of troubles compiling multiarch wine from source in the past, and I finally did it today.
However, I have one problem: when I run overwatch, it says "Game Initialization Failed." I have tried this under XP, 7, 10.

These are the packages that the 64bit configure says I'm missing
configure: libhal 64-bit development files not found, no legacy dynamic device support.
configure: gstreamer-1.0 base plugins 64-bit development files not found, gstreamer support disabled
configure: OSS sound system found but too old (OSSv4 needed), OSS won't be supported.

These are for the 32:
configure: XShm 32-bit development files not found, X Shared Memory won't be supported.
configure: XShape 32-bit development files not found, XShape won't be supported.
configure: libGLU 32-bit development files not found, GLU won't be supported.
configure: libdbus 32-bit development files not found, no dynamic device support.
configure: lib(n)curses 32-bit development files not found, curses won't be supported.
configure: libsane 32-bit development files not found, scanners won't be supported.
configure: GTK3 32-bit development files not found, GTK themes won't be supported.
configure: gstreamer-1.0 base plugins 32-bit development files not found, gstreamer support disabled
configure: OSS sound system found but too old (OSSv4 needed), OSS won't be supported.
configure: libudev 32-bit development files not found, plug and play won't be supported.
configure: libcapi20 32-bit development files not found, ISDN won't be supported.
configure: libcups 32-bit development files not found, CUPS won't be supported.
configure: libmpg123 32-bit development files not found (or too old), mp3 codec won't be supported.
configure: WARNING: libxslt 32-bit development files not found, xslt won't be supported.

Now it's worth noting that I installed this wine as normal user to a directory other that /usr, but I don't think that should be a problem.

Any help would be appreciated. Thanks!

**Comment by Amblypygid** [comment]
I'm on OpenSUSE Leap 42.2, if that's important.

**Comment by gamax92** [comment]
It sounds like the wrong copy of wine is being ran, you'll get this error with an unpatched wine.
Make sure the one you're running is the wine64 built from this repo.

Also, for reference what instructions did you use for building wine in OpenSUSE?

**Comment by Amblypygid** [comment]
I used the instructions near the bottom of [this post](https://github.com/gamax92/wine-overwatch/issues/5). I have tried running the overwatch executable (bot the launcher and the game itself) with the wine and wine64 executables build from this repo. I gave them a directory to be installed to, so as not to touch my root partition: /home/blah/blah/blah/wine-build/wine-install
Is there something special I need to do to enable the patches when I build from this repo?

**Comment by Amblypygid** [comment]
Hm. I tried cleaning out my wine prefix and trying again. Didn't work.

**Comment by Amblypygid** [comment]
unless I said "wine64 ~/Downloads/Overwatch-Setup.exe" rather than "./wine64 ~/Downloads/Overwatch-Setup.exe"... trying again, making sure to use the right wine.

**Comment by Amblypygid** [comment]
Okay, That didn't help. But I've noticed that I've got a wine version mismatch error, even when this repo is the only wine on my system. I believe it is 532/528. I'm really not sure what's going on here.

**Comment by Amblypygid** [comment]
Okay, I've rebuilt it all from scratch, and I'm getting the error: /usr/local/bin/wine: error while loading shared libraries: libwine.so.1: wrong ELF class: ELFCLASS64

Any ideas?

**Comment by Paktosan** [comment]
Can you be so kind to try this repository for me? http://download.opensuse.org/repositories/home:/Paktosan:/branches:/Emulators:/Wine/openSUSE_Leap_42.2/ 
This is my version of it but built with the SUSE specific stuff AND the overwatch patches. However it still is at version 2.7, I am gonna try to update it later today.

**Comment by Paktosan** [comment]
Ok, for openSUSE 42.2 you have to add the following two repositories:
1. http://download.opensuse.org/repositories/Emulators:/Wine/openSUSE_Leap_42.2/
2. http://download.opensuse.org/repositories/home:/Paktosan/openSUSE_Leap_42.2/
Also the second repository must have a higher priority than all other repositorys that contain anything wine related. You can then simply install wine via yast or zypper. My version always has overwatch in its version name.

**Comment by Amblypygid** [comment]
Right, I'm home from work now. Let me give this a try. *cracks knuckles* :D

**Comment by Amblypygid** [comment]
It works nicely (or as nicely as can be expected!). Thanks, James and Julian! I'll have an increasing amount of fun as the development of DX11 in wine progresses. Cheers!

**Comment by gamax92** [comment]
@Paktosan for reference, how did you go about building this for openSUSE, anything special needed?

**Comment by Paktosan** [comment]
@gamax92 I used the openSUSE Build Service and just copied the configuration from the official wine build. You can see the source here: https://build.opensuse.org/package/show/home:Paktosan/wine-overwatch
Building locally is possible by using the osc tool which then uses a container to isolate the build environment. In theory the build service could also build for other distributions but the current .spec file is not suitable for that.

**Comment by zekesonxx** [comment]
Closing since this got resolved a while ago
